<?php

function kontak()
{
    return "https://wa.me/6285264153647";
}


function param()
{
    $param = collect(
        [
            [
                'dimensi_id' => 1,
                'id' => 1,
                'tujuan' => 'Mengukur seberapa komprehensif program peningkatan skill manajemen risiko, kekuatan budaya manajemen risiko, serta relevansi RMA dengan praktik manajemen risiko secara keseluruhan',
                'deskripsi' => 'Setiap insan Perusahaan memahami visi dan misi perusahaan.',
                'ref' => 'Pedoman Lama - Aspek 2 "Perancangan Kerangka Kerja" Pedoman Penerapan Manajemen Risiko berbasis Governance 2012 (halaman 20)',
                'pertanyaan' => 'Apakah memiliki perusahaan memiliki visi dan misi yang ditetapkan secara formal dan telah dipahami oleh seluruh pegawai?',
                'skor0' => 'Semua insan perusahaan tidak memahami visi dan misi',
                'skor1' => 'Hanya Direksi dan Dekom memahami visi dan misi perusahaan',
                'skor2' => 'Visi dan misi telah dipahami Direksi & Dekom dan sebagian kecil middle management (Kadiv)',
                'skor3' => 'Sebagian besar Kadiv dan pegawai memahami visi dan misi perusahaan (50%-75%)',
                'skor4' => 'Sebagian besar Kadiv dan pegawai memahami visi dan misi perusahaan (>=75%)',
                'skor5' => 'Seluruh insan perusahaan memahami visi dan misi perusahaan (>95%)',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 'Kuesioner Persepsi, Reviu dokumen',
                'catatan' => '',
                'hasilreviu',
            ],
            [
                'dimensi_id' => 1,
                'id' => 2,
                'tujuan' => 'Mengukur seberapa komprehensif program peningkatan skill manajemen risiko, kekuatan budaya manajemen risiko, serta relevansi RMA dengan praktik manajemen risiko secara keseluruhan    ',
                'deskripsi' => 'Perusahaan telah memiliki strategi dan arah penerapan Manajemen Risiko (misal: road map/master plan Manajemen Risiko)',
                'ref' => 'Pedoman Lama - Aspek 2 "Perancangan Kerangka Kerja" ISO 31000:2018',
                'pertanyaan' => 'Bagaimana perushaan menetapkan strategi dan arah penerapan manajemen risiko?',
                'skor0' => 'Perusahaan belum menetapkan strategi dan arah penerapan manajemen risiko',
                'skor1' => 'Perusahaan telah memiliki strategi dan arah penerapan manajemen risiko baik jangka pendek, menengah dan panjang.',
                'skor2' => 'Perusahaan telah memiliki strategi dan arah penerapan manajemen risiko baik jangka pendek, mengengah, dan panjang, perusahaan telah melakukan evaluasi atas strategi dan arah penerapan manajemen risiko tersebut. Namun, belum disosialisasikan.',
                'skor3' => 'Perusahaan telah memiliki strategi dan arah penerapan manajemen risiko baik jangka pendek, menengah dan panjang. Dan sudah dilaksanakan',
                'skor4' => 'Perusahaan telah memiliki strategi dan arah penerapan manajemen risiko baik jangka pendek, mengengah,dan telah dilaksanakan oleh seluruh organ perusahaan, dan dilakukan evaluasi secara berkala',
                'skor5' => 'Perusahaan telah memiliki strategi dan arah penerapan manajemen risiko baik jangka pendek, menengah dan panjang dan telah dipahami dilaksanakan oleh seluruh organ perusahaan, dan telah dilakukan evaluasi secara berkala. 
                Dilakukan secara efektif dan improved.',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 3,
                'tujuan' => 'Tujuan 3',
                'deskripsi' => 'Deskripsi 3',
                'ref' => 'Ref 3',
                'pertanyaan' => 'Pertanyaan 3',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 4,
                'tujuan' => 'Tujuan 4',
                'deskripsi' => 'Deskripsi 4',
                'ref' => 'Ref 4',
                'pertanyaan' => 'Pertanyaan 4',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 5,
                'tujuan' => 'Tujuan 5',
                'deskripsi' => 'Deskripsi 5',
                'ref' => 'Ref 5',
                'pertanyaan' => 'Pertanyaan 5',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 6,
                'tujuan' => 'Tujuan 6',
                'deskripsi' => 'Deskripsi 6',
                'ref' => 'Ref 6',
                'pertanyaan' => 'Pertanyaan 6',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 7,
                'tujuan' => 'Tujuan 7',
                'deskripsi' => 'Deskripsi 7',
                'ref' => 'Ref 7',
                'pertanyaan' => 'Pertanyaan 7',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 8,
                'tujuan' => 'Tujuan 8',
                'deskripsi' => 'Deskripsi 8',
                'ref' => 'Ref 8',
                'pertanyaan' => 'Pertanyaan 8',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 9,
                'tujuan' => 'Tujuan 9',
                'deskripsi' => 'Deskripsi 9',
                'ref' => 'Ref 9',
                'pertanyaan' => 'Pertanyaan 9',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 10,
                'tujuan' => 'Tujuan 10',
                'deskripsi' => 'Deskripsi 10',
                'ref' => 'Ref 10',
                'pertanyaan' => 'Pertanyaan 10',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 11,
                'tujuan' => 'Tujuan 11',
                'deskripsi' => 'Deskripsi 11',
                'ref' => 'Ref 11',
                'pertanyaan' => 'Pertanyaan 11',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 12,
                'tujuan' => 'Tujuan 12',
                'deskripsi' => 'Deskripsi 12',
                'ref' => 'Ref 12',
                'pertanyaan' => 'Pertanyaan 12',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 13,
                'tujuan' => 'Tujuan 13',
                'deskripsi' => 'Deskripsi 13',
                'ref' => 'Ref 13',
                'pertanyaan' => 'Pertanyaan 13',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 14,
                'tujuan' => 'Tujuan 14',
                'deskripsi' => 'Deskripsi 14',
                'ref' => 'Ref 14',
                'pertanyaan' => 'Pertanyaan 14',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 15,
                'tujuan' => 'Tujuan 15',
                'deskripsi' => 'Deskripsi 15',
                'ref' => 'Ref 15',
                'pertanyaan' => 'Pertanyaan 15',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 16,
                'tujuan' => 'Tujuan 16',
                'deskripsi' => 'Deskripsi 16',
                'ref' => 'Ref 16',
                'pertanyaan' => 'Pertanyaan 16',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 17,
                'tujuan' => 'Tujuan 17',
                'deskripsi' => 'Deskripsi 17',
                'ref' => 'Ref 17',
                'pertanyaan' => 'Pertanyaan 17',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 18,
                'tujuan' => 'Tujuan 18',
                'deskripsi' => 'Deskripsi 18',
                'ref' => 'Ref 18',
                'pertanyaan' => 'Pertanyaan 18',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 19,
                'tujuan' => 'Tujuan 19',
                'deskripsi' => 'Deskripsi 19',
                'ref' => 'Ref 19',
                'pertanyaan' => 'Pertanyaan 19',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 1,
                'id' => 20,
                'tujuan' => 'Tujuan 20',
                'deskripsi' => 'Deskripsi 20',
                'ref' => 'Ref 20',
                'pertanyaan' => 'Pertanyaan 20',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 21,
                'tujuan' => 'Tujuan 21',
                'deskripsi' => 'Deskripsi 21',
                'ref' => 'Ref 21',
                'pertanyaan' => 'Pertanyaan 21',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 22,
                'tujuan' => 'Tujuan 22',
                'deskripsi' => 'Deskripsi 22',
                'ref' => 'Ref 22',
                'pertanyaan' => 'Pertanyaan 22',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 23,
                'tujuan' => 'Tujuan 23',
                'deskripsi' => 'Deskripsi 23',
                'ref' => 'Ref 23',
                'pertanyaan' => 'Pertanyaan 23',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 24,
                'tujuan' => 'Tujuan 24',
                'deskripsi' => 'Deskripsi 24',
                'ref' => 'Ref 24',
                'pertanyaan' => 'Pertanyaan 24',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 25,
                'tujuan' => 'Tujuan 25',
                'deskripsi' => 'Deskripsi 25',
                'ref' => 'Ref 25',
                'pertanyaan' => 'Pertanyaan 25',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 26,
                'tujuan' => 'Tujuan 26',
                'deskripsi' => 'Deskripsi 26',
                'ref' => 'Ref 26',
                'pertanyaan' => 'Pertanyaan 26',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 27,
                'tujuan' => 'Tujuan 27',
                'deskripsi' => 'Deskripsi 27',
                'ref' => 'Ref 27',
                'pertanyaan' => 'Pertanyaan 27',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 28,
                'tujuan' => 'Tujuan 28',
                'deskripsi' => 'Deskripsi 28',
                'ref' => 'Ref 28',
                'pertanyaan' => 'Pertanyaan 28',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 29,
                'tujuan' => 'Tujuan 29',
                'deskripsi' => 'Deskripsi 29',
                'ref' => 'Ref 29',
                'pertanyaan' => 'Pertanyaan 29',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 30,
                'tujuan' => 'Tujuan 30',
                'deskripsi' => 'Deskripsi 30',
                'ref' => 'Ref 30',
                'pertanyaan' => 'Pertanyaan 30',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 31,
                'tujuan' => 'Tujuan 31',
                'deskripsi' => 'Deskripsi 31',
                'ref' => 'Ref 31',
                'pertanyaan' => 'Pertanyaan 31',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 32,
                'tujuan' => 'Tujuan 32',
                'deskripsi' => 'Deskripsi 32',
                'ref' => 'Ref 32',
                'pertanyaan' => 'Pertanyaan 32',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 33,
                'tujuan' => 'Tujuan 33',
                'deskripsi' => 'Deskripsi 33',
                'ref' => 'Ref 33',
                'pertanyaan' => 'Pertanyaan 33',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 34,
                'tujuan' => 'Tujuan 34',
                'deskripsi' => 'Deskripsi 34',
                'ref' => 'Ref 34',
                'pertanyaan' => 'Pertanyaan 34',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 35,
                'tujuan' => 'Tujuan 35',
                'deskripsi' => 'Deskripsi 35',
                'ref' => 'Ref 35',
                'pertanyaan' => 'Pertanyaan 35',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 36,
                'tujuan' => 'Tujuan 36',
                'deskripsi' => 'Deskripsi 36',
                'ref' => 'Ref 36',
                'pertanyaan' => 'Pertanyaan 36',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 37,
                'tujuan' => 'Tujuan 37',
                'deskripsi' => 'Deskripsi 37',
                'ref' => 'Ref 37',
                'pertanyaan' => 'Pertanyaan 37',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 38,
                'tujuan' => 'Tujuan 38',
                'deskripsi' => 'Deskripsi 38',
                'ref' => 'Ref 38',
                'pertanyaan' => 'Pertanyaan 38',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 39,
                'tujuan' => 'Tujuan 39',
                'deskripsi' => 'Deskripsi 39',
                'ref' => 'Ref 39',
                'pertanyaan' => 'Pertanyaan 39',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 2,
                'id' => 40,
                'tujuan' => 'Tujuan 40',
                'deskripsi' => 'Deskripsi 40',
                'ref' => 'Ref 40',
                'pertanyaan' => 'Pertanyaan 40',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 41,
                'tujuan' => 'Tujuan 41',
                'deskripsi' => 'Deskripsi 41',
                'ref' => 'Ref 41',
                'pertanyaan' => 'Pertanyaan 41',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 42,
                'tujuan' => 'Tujuan 42',
                'deskripsi' => 'Deskripsi 42',
                'ref' => 'Ref 42',
                'pertanyaan' => 'Pertanyaan 42',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 43,
                'tujuan' => 'Tujuan 43',
                'deskripsi' => 'Deskripsi 43',
                'ref' => 'Ref 43',
                'pertanyaan' => 'Pertanyaan 43',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 44,
                'tujuan' => 'Tujuan 44',
                'deskripsi' => 'Deskripsi 44',
                'ref' => 'Ref 44',
                'pertanyaan' => 'Pertanyaan 44',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 45,
                'tujuan' => 'Tujuan 45',
                'deskripsi' => 'Deskripsi 45',
                'ref' => 'Ref 45',
                'pertanyaan' => 'Pertanyaan 45',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 46,
                'tujuan' => 'Tujuan 46',
                'deskripsi' => 'Deskripsi 46',
                'ref' => 'Ref 46',
                'pertanyaan' => 'Pertanyaan 46',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 47,
                'tujuan' => 'Tujuan 47',
                'deskripsi' => 'Deskripsi 47',
                'ref' => 'Ref 47',
                'pertanyaan' => 'Pertanyaan 47',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 48,
                'tujuan' => 'Tujuan 48',
                'deskripsi' => 'Deskripsi 48',
                'ref' => 'Ref 48',
                'pertanyaan' => 'Pertanyaan 48',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 49,
                'tujuan' => 'Tujuan 49',
                'deskripsi' => 'Deskripsi 49',
                'ref' => 'Ref 49',
                'pertanyaan' => 'Pertanyaan 49',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 50,
                'tujuan' => 'Tujuan 50',
                'deskripsi' => 'Deskripsi 50',
                'ref' => 'Ref 50',
                'pertanyaan' => 'Pertanyaan 50',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 51,
                'tujuan' => 'Tujuan 51',
                'deskripsi' => 'Deskripsi 51',
                'ref' => 'Ref 51',
                'pertanyaan' => 'Pertanyaan 51',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 52,
                'tujuan' => 'Tujuan 52',
                'deskripsi' => 'Deskripsi 52',
                'ref' => 'Ref 52',
                'pertanyaan' => 'Pertanyaan 52',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 53,
                'tujuan' => 'Tujuan 53',
                'deskripsi' => 'Deskripsi 53',
                'ref' => 'Ref 53',
                'pertanyaan' => 'Pertanyaan 53',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 54,
                'tujuan' => 'Tujuan 54',
                'deskripsi' => 'Deskripsi 54',
                'ref' => 'Ref 54',
                'pertanyaan' => 'Pertanyaan 54',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 55,
                'tujuan' => 'Tujuan 55',
                'deskripsi' => 'Deskripsi 55',
                'ref' => 'Ref 55',
                'pertanyaan' => 'Pertanyaan 55',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 56,
                'tujuan' => 'Tujuan 56',
                'deskripsi' => 'Deskripsi 56',
                'ref' => 'Ref 56',
                'pertanyaan' => 'Pertanyaan 56',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 57,
                'tujuan' => 'Tujuan 57',
                'deskripsi' => 'Deskripsi 57',
                'ref' => 'Ref 57',
                'pertanyaan' => 'Pertanyaan 57',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 58,
                'tujuan' => 'Tujuan 58',
                'deskripsi' => 'Deskripsi 58',
                'ref' => 'Ref 58',
                'pertanyaan' => 'Pertanyaan 58',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 59,
                'tujuan' => 'Tujuan 59',
                'deskripsi' => 'Deskripsi 59',
                'ref' => 'Ref 59',
                'pertanyaan' => 'Pertanyaan 59',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 3,
                'id' => 60,
                'tujuan' => 'Tujuan 60',
                'deskripsi' => 'Deskripsi 60',
                'ref' => 'Ref 60',
                'pertanyaan' => 'Pertanyaan 60',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 61,
                'tujuan' => 'Tujuan 61',
                'deskripsi' => 'Deskripsi 61',
                'ref' => 'Ref 61',
                'pertanyaan' => 'Pertanyaan 61',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 62,
                'tujuan' => 'Tujuan 62',
                'deskripsi' => 'Deskripsi 62',
                'ref' => 'Ref 62',
                'pertanyaan' => 'Pertanyaan 62',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 63,
                'tujuan' => 'Tujuan 63',
                'deskripsi' => 'Deskripsi 63',
                'ref' => 'Ref 63',
                'pertanyaan' => 'Pertanyaan 63',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 64,
                'tujuan' => 'Tujuan 64',
                'deskripsi' => 'Deskripsi 64',
                'ref' => 'Ref 64',
                'pertanyaan' => 'Pertanyaan 64',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 65,
                'tujuan' => 'Tujuan 65',
                'deskripsi' => 'Deskripsi 65',
                'ref' => 'Ref 65',
                'pertanyaan' => 'Pertanyaan 65',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 66,
                'tujuan' => 'Tujuan 66',
                'deskripsi' => 'Deskripsi 66',
                'ref' => 'Ref 66',
                'pertanyaan' => 'Pertanyaan 66',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 67,
                'tujuan' => 'Tujuan 67',
                'deskripsi' => 'Deskripsi 67',
                'ref' => 'Ref 67',
                'pertanyaan' => 'Pertanyaan 67',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 68,
                'tujuan' => 'Tujuan 68',
                'deskripsi' => 'Deskripsi 68',
                'ref' => 'Ref 68',
                'pertanyaan' => 'Pertanyaan 68',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 69,
                'tujuan' => 'Tujuan 69',
                'deskripsi' => 'Deskripsi 69',
                'ref' => 'Ref 69',
                'pertanyaan' => 'Pertanyaan 69',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 70,
                'tujuan' => 'Tujuan 70',
                'deskripsi' => 'Deskripsi 70',
                'ref' => 'Ref 70',
                'pertanyaan' => 'Pertanyaan 70',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 71,
                'tujuan' => 'Tujuan 71',
                'deskripsi' => 'Deskripsi 71',
                'ref' => 'Ref 71',
                'pertanyaan' => 'Pertanyaan 71',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 72,
                'tujuan' => 'Tujuan 72',
                'deskripsi' => 'Deskripsi 72',
                'ref' => 'Ref 72',
                'pertanyaan' => 'Pertanyaan 72',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 73,
                'tujuan' => 'Tujuan 73',
                'deskripsi' => 'Deskripsi 73',
                'ref' => 'Ref 73',
                'pertanyaan' => 'Pertanyaan 73',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 74,
                'tujuan' => 'Tujuan 74',
                'deskripsi' => 'Deskripsi 74',
                'ref' => 'Ref 74',
                'pertanyaan' => 'Pertanyaan 74',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 75,
                'tujuan' => 'Tujuan 75',
                'deskripsi' => 'Deskripsi 75',
                'ref' => 'Ref 75',
                'pertanyaan' => 'Pertanyaan 75',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 76,
                'tujuan' => 'Tujuan 76',
                'deskripsi' => 'Deskripsi 76',
                'ref' => 'Ref 76',
                'pertanyaan' => 'Pertanyaan 76',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 77,
                'tujuan' => 'Tujuan 77',
                'deskripsi' => 'Deskripsi 77',
                'ref' => 'Ref 77',
                'pertanyaan' => 'Pertanyaan 77',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 78,
                'tujuan' => 'Tujuan 78',
                'deskripsi' => 'Deskripsi 78',
                'ref' => 'Ref 78',
                'pertanyaan' => 'Pertanyaan 78',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 79,
                'tujuan' => 'Tujuan 79',
                'deskripsi' => 'Deskripsi 79',
                'ref' => 'Ref 79',
                'pertanyaan' => 'Pertanyaan 79',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 4,
                'id' => 80,
                'tujuan' => 'Tujuan 80',
                'deskripsi' => 'Deskripsi 80',
                'ref' => 'Ref 80',
                'pertanyaan' => 'Pertanyaan 80',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 81,
                'tujuan' => 'Tujuan 81',
                'deskripsi' => 'Deskripsi 81',
                'ref' => 'Ref 81',
                'pertanyaan' => 'Pertanyaan 81',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 82,
                'tujuan' => 'Tujuan 82',
                'deskripsi' => 'Deskripsi 82',
                'ref' => 'Ref 82',
                'pertanyaan' => 'Pertanyaan 82',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 83,
                'tujuan' => 'Tujuan 83',
                'deskripsi' => 'Deskripsi 83',
                'ref' => 'Ref 83',
                'pertanyaan' => 'Pertanyaan 83',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 84,
                'tujuan' => 'Tujuan 84',
                'deskripsi' => 'Deskripsi 84',
                'ref' => 'Ref 84',
                'pertanyaan' => 'Pertanyaan 84',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 85,
                'tujuan' => 'Tujuan 85',
                'deskripsi' => 'Deskripsi 85',
                'ref' => 'Ref 85',
                'pertanyaan' => 'Pertanyaan 85',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 86,
                'tujuan' => 'Tujuan 86',
                'deskripsi' => 'Deskripsi 86',
                'ref' => 'Ref 86',
                'pertanyaan' => 'Pertanyaan 86',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 87,
                'tujuan' => 'Tujuan 87',
                'deskripsi' => 'Deskripsi 87',
                'ref' => 'Ref 87',
                'pertanyaan' => 'Pertanyaan 87',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 88,
                'tujuan' => 'Tujuan 88',
                'deskripsi' => 'Deskripsi 88',
                'ref' => 'Ref 88',
                'pertanyaan' => 'Pertanyaan 88',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 89,
                'tujuan' => 'Tujuan 89',
                'deskripsi' => 'Deskripsi 89',
                'ref' => 'Ref 89',
                'pertanyaan' => 'Pertanyaan 89',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 90,
                'tujuan' => 'Tujuan 90',
                'deskripsi' => 'Deskripsi 90',
                'ref' => 'Ref 90',
                'pertanyaan' => 'Pertanyaan 90',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 91,
                'tujuan' => 'Tujuan 91',
                'deskripsi' => 'Deskripsi 91',
                'ref' => 'Ref 91',
                'pertanyaan' => 'Pertanyaan 91',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 92,
                'tujuan' => 'Tujuan 92',
                'deskripsi' => 'Deskripsi 92',
                'ref' => 'Ref 92',
                'pertanyaan' => 'Pertanyaan 92',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 93,
                'tujuan' => 'Tujuan 93',
                'deskripsi' => 'Deskripsi 93',
                'ref' => 'Ref 93',
                'pertanyaan' => 'Pertanyaan 93',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 94,
                'tujuan' => 'Tujuan 94',
                'deskripsi' => 'Deskripsi 94',
                'ref' => 'Ref 94',
                'pertanyaan' => 'Pertanyaan 94',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 95,
                'tujuan' => 'Tujuan 95',
                'deskripsi' => 'Deskripsi 95',
                'ref' => 'Ref 95',
                'pertanyaan' => 'Pertanyaan 95',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 96,
                'tujuan' => 'Tujuan 96',
                'deskripsi' => 'Deskripsi 96',
                'ref' => 'Ref 96',
                'pertanyaan' => 'Pertanyaan 96',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 97,
                'tujuan' => 'Tujuan 97',
                'deskripsi' => 'Deskripsi 97',
                'ref' => 'Ref 97',
                'pertanyaan' => 'Pertanyaan 97',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 98,
                'tujuan' => 'Tujuan 98',
                'deskripsi' => 'Deskripsi 98',
                'ref' => 'Ref 98',
                'pertanyaan' => 'Pertanyaan 98',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 99,
                'tujuan' => 'Tujuan 99',
                'deskripsi' => 'Deskripsi 99',
                'ref' => 'Ref 99',
                'pertanyaan' => 'Pertanyaan 99',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'skor2',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
            [
                'dimensi_id' => 5,
                'id' => 100,
                'tujuan' => 'Tujuan 100',
                'deskripsi' => 'Deskripsi 100',
                'ref' => 'Ref 100',
                'pertanyaan' => 'Pertanyaan 100',
                'skor0' => 'skor0',
                'skor1' => 'skor1',
                'skor2' => 'Visi dan misi telah dipahami Direksi & Dekom dan sebagian kecil middle management (Kadiv)',
                'skor3' => 'skor3',
                'skor4' => 'skor4',
                'skor5' => 'skor5',
                'per_info_d' => 1,
                'per_info_w' => 1,
                'per_info_l' => 1,
                'per_info_o' => 0,
                'sumberinformasi' => 0,
            ],
        ],
    );

    return $param;
}
